[package]
name = "tc_aead_cipher"
description = "Authenticated encryption with associated data (AEAD) contracts."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
alloc = ["tc_zeroize/alloc"]

[dependencies]
tc_block_cipher = "0.1.0"
tc_constant_time = "0.1.0"
tc_runtime = "0.1.0"
tc_zeroize = "0.1.0"

[dev-dependencies]
tc_aes = "0.1.0"
tc_dstu7624 = "0.1.0"